services:
  # Nginx acting as a Reverse Proxy
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
    networks:
      - internal

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # Container: .NET MVC (Educational Platform - CORE)
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=$${MYSQL_DATABASE};User=$${MYSQL_USER};Password=$${MYSQL_PASSWORD};
      - FinancialEngine__BaseUrl=http://calculation-engine:8000/api/
    depends_on:
      - db
    networks:
      - internal

  # Container: Django (Financial Calculation Engine)
  calculation-engine:
    build:
      context: ./src/backend
    environment:
      - DJANGO_SECRET_KEY=$${DJANGO_SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=calculation-engine,localhost,dec-plataforma.duckdns.org
    networks:
      - internal

  # Container: MySQL (Database)
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - internal

# Internal Docker Network
networks:
  internal:
    driver: bridge

volumes:
  mysql_data:
